"""Create reproducible EDA and data documentation from actual generated records."""
import sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
import json
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from factory.data import FEATURES,prepare,temporal_split

raw=pd.read_csv(ROOT/'data/sensors.csv')
data,audit=prepare(raw,pd.read_csv(ROOT/'data/production.csv'))
parts=temporal_split(data)
plt.style.use('default')
fig,axes=plt.subplots(2,3,figsize=(16,9),layout='constrained')
fig.suptitle('AI Factory — synthetic dataset analysis',fontsize=21,fontweight='bold')
raw[FEATURES[:5]].isna().sum().plot.bar(ax=axes[0,0],color='#315c74',title='Missing sensor values before cleaning')
axes[0,0].tick_params(axis='x',rotation=25)
for label,group in data.groupby('failure_next_6h'):
    axes[0,1].hist(group.vibration,bins=30,alpha=.6,label=f'Future failure = {label}',density=True)
axes[0,1].set(title='Vibration distributions overlap',xlabel='Vibration (mm/s)',ylabel='Density');axes[0,1].legend()
corr=data[['temperature','vibration','pressure','rpm','load','failure_next_6h']].corr()
im=axes[0,2].imshow(corr,vmin=-1,vmax=1,cmap='RdBu_r')
axes[0,2].set_xticks(range(len(corr)),corr.columns,rotation=45,ha='right',fontsize=8)
axes[0,2].set_yticks(range(len(corr)),corr.columns,fontsize=8);axes[0,2].set_title('Correlation is not causation');fig.colorbar(im,ax=axes[0,2],shrink=.7)
data.groupby('machine_id').failure_next_6h.mean().plot.bar(ax=axes[1,0],color='#315c74',title='Synthetic failure-label prevalence by machine')
axes[1,0].set_ylabel('Fraction');axes[1,0].tick_params(axis='x',rotation=0)
counts=pd.DataFrame({name:part.failure_next_6h.value_counts() for name,part in zip(['train','validation','test'],parts)}).fillna(0).T
counts.plot.bar(ax=axes[1,1],stacked=True,title='Chronological splits after six-hour purges');axes[1,1].tick_params(axis='x',rotation=0);axes[1,1].legend(['No failure','Failure'])
cm=np.array(json.loads((ROOT/'artifacts/confusion_matrix.json').read_text()))
axes[1,2].imshow(cm,cmap='Blues')
for (i,j),value in np.ndenumerate(cm): axes[1,2].text(j,i,str(value),ha='center',va='center',fontsize=20,color='white' if value>cm.max()/2 else 'black')
axes[1,2].set(title='Selected model test confusion matrix',xlabel='Predicted label',ylabel='Actual label',xticks=[0,1],yticks=[0,1])
fig.savefig(ROOT/'outputs/data-analysis.png',dpi=150);plt.close(fig)
text=f'''# Data and model evidence

All factory records were generated by factory/data.py with seed 42. No real production observations or proprietary manuals are included. Product images are synthetic bearing drawings, not photographs. Public pretrained Qwen weights are an optional separate language component.

## Cleaning evidence

- Raw sensor rows: {len(raw)}; cleaned rows: {len(data)}.
- Removed duplicate/invalid-key rows: {audit['removed_rows']}.
- Invalid sensor-range values converted to missing: {audit['invalid_sensor_values']}.
- Remaining missing engineered feature values: {audit['remaining_missing_features']} (training-fit median imputation handles these).
- Labels indicating future failure: {data.failure_next_6h.mean():.1%}.
- Split sizes after purges: train {len(parts[0])}, validation {len(parts[1])}, test {len(parts[2])}.

Range checks reject physically invalid readings such as negative pressure. Plausible high vibration and temperature are retained because removing them would suppress the fault signal. Forward-fill uses only preceding observations within a machine. Six-row rolling statistics assume the hourly cadence of the demo; uploaded irregular histories require a sampling policy before operational use.

Production records are joined one-to-one on machine and timestamp. Reject rate is rejects divided by valid positive units, with rejects constrained between zero and units. It contributes to model inference and the digital twin. Single-image confidence is never substituted for batch reject rate.

## Leakage and limitations

The failure target uses latent wear in the following six hours. Those future values are not model inputs. A six-hour purge separates training/validation and validation/test observations. Neural early stopping uses validation loss and maintenance selection uses validation F1. Original test results do not select the model.

The same synthetic generator and fleet appear in each temporal split, so these results do not establish generalization to real machinery or unseen factories. Image splits use different seeds, but share the same drawing generator. No calibration or confidence intervals are claimed.

## Error evidence

Selected-model test confusion matrix (rows actual, columns predicted): {cm.tolist()}.
False negatives: {cm[1,0]}; false positives: {cm[0,1]}.
Overlapping noisy wear signals produce ambiguous decisions around the fixed 0.5 threshold. Inspect artifacts/maintenance_errors.csv for the actual cases. False negatives could miss failures; false positives could lead to unnecessary review. The app therefore keeps a human decision step.

The independent controlled-learning rehearsal exhibits distribution shift: its candidate failed the minimum validation gate and was withheld. This is a demonstrated failure path, not evidence of successful adaptation.

See data-analysis.png for measured distributions, correlations, class balance and confusion counts.
'''
(ROOT/'outputs/data-and-model-card.md').write_text(text,encoding='utf-8')
print('EDA figure and data/model card generated from actual records.')
